import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function fixNotificationDates() {
  console.log('Fixing notification dates...');
  
  const notifications = await prisma.notification.findMany({
    where: {
      message: {
        contains: 'vence el',
      },
    },
  });

  console.log(`Found ${notifications.length} relevant notifications.`);

  for (const n of notifications) {
    // Regex to find dates like M/D/YYYY or MM/DD/YYYY
    // Message looks like: "El contrato de la propiedad en XXX vence el M/D/YYYY."
    const match = n.message.match(/vence el (\d{1,2})\/(\d{1,2})\/(\d{4})/);
    
    if (match) {
      const [fullMatch, month, day, year] = match;
      
      // If month > 12, it's definitely D/M/Y already (or error)
      // But we want to ensure D/M/Y. 
      // If we are here, we suspect it's currently M/D/Y.
      
      // Check if it looks like M/D/Y (month <= 12)
      const m = parseInt(month);
      const d = parseInt(day);
      
      if (m <= 12 && d > 12) {
        // Definitely M/D/Y needing swap
        const newDate = `${day}/${month}/${year}`;
        const newMessage = n.message.replace(fullMatch, `vence el ${newDate}`);
        
        await prisma.notification.update({
          where: { id: n.id },
          data: { message: newMessage },
        });
        console.log(`Updated notification ${n.id}: ${newDate}`);
      } else if (m <= 12 && d <= 12 && m !== d) {
        // Ambiguous. Let's assume it's M/D/Y and swap if it came from the bug period.
        // For safety, let's just swap if it matches the pattern exactly 
        // as generated by US locale.
        const newDate = `${day}/${month}/${year}`;
        const newMessage = n.message.replace(fullMatch, `vence el ${newDate}`);
        
        await prisma.notification.update({
          where: { id: n.id },
          data: { message: newMessage },
        });
        console.log(`Updated ambiguous notification ${n.id}: ${newDate}`);
      }
    }
  }

  console.log('Done.');
}

fixNotificationDates()
  .catch(e => console.error(e))
  .finally(() => prisma.$disconnect());
